name: personal_expense_tracker
description: Flutter Developer Technical Assessment
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.5.6
  go_router: ^14.2.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  json_annotation: ^4.9.0
  intl: ^0.19.0
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    
